import AuthContext from "./context/AuthContext";
import ToasterContex from "./context/ToasterContex";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <ToasterContex />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
